FROM openjdk:8-jre-alpine

RUN mkdir /app

WORKDIR /app

ADD $TRAVIS_BUILD_DIR/services/target/microservices-service-api-2.5.0-SNAPSHOT.jar /app

EXPOSE 8080

CMD ["java", "-jar", "/app/microservices-service-api-2.5.0-SNAPSHOT.jar"]
