kumuluzee:
  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://postgres:5432/adverts
      username: postgres
      password: postgres
      max-pool-size: 20
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                     <Configuration name="services">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                               <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                             <Socket name="socket" host="4da2b37b-f061-42e4-bedf-fe629953cccf-ls.logit.io" port="15015">
                                  <JsonLayout properties="true" complete="false" compact="true" eventEol="true" charset="UTF-8"/>

                                </Socket>
                        </Appenders>
                        <Loggers>

                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                                <AppenderRef ref="socket"/>
                                <!-- <AppenderRef ref="logstash" level="trace"/>-->
                             </Root>
                        </Loggers>
                    </Configuration>'
  config:
      start-retry-delay-ms: 500
      max-retry-delay-ms: 900000
      etcd:
        hosts: http://etcd:2379
