kumuluzee:
  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://postgres:5432/postgres
      username: postgres
      password: postgres
      max-pool-size: 20
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                     <Configuration name="profiles">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n [%t] %-5level %logger{36} - %msg%n"/>
                            </Console>
                             <Socket name="socket" host="23a869c8-9dce-48d9-9e69-dfad33015468-ls.logit.io" port="23127">
                                  <JsonLayout properties="true"/>
                                </Socket>
                        </Appenders>
                        <Loggers>
                        <Logger name="com.kumuluz.ee.samples.microservices.simple.CartResource" level="trace">
                          <AppenderRef ref="Console"/>
                        </Logger>
                            <!-- Default logger -->
                            <Root level="info">
                                <AppenderRef ref="console"/>
                                <AppenderRef ref="socket"/>
                             </Root>
                        </Loggers>
                    </Configuration>'
    loggers:
      - name: ''
        level: INFO
  config:
      start-retry-delay-ms: 500
      max-retry-delay-ms: 900000
      etcd:
        hosts: http://etcd:2379
